
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jayson
 */
public class SJF extends javax.swing.JFrame {

    /**
     * Creates new form Algo
     */
    public SJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField31 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("P1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("P2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("P3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("P4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("P5");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("P6");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 30, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AT");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 30, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 30, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 30, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("WT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 30, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ATA  =");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 120, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("AWT =");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 120, 40));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 30));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 60, 30));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 60, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 60, 30));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 60, 30));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 60, 30));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 60, 30));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 60, 30));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 60, 30));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 60, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 60, 30));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 60, 30));

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 60, 30));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 60, 30));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 60, 30));

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 30));

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 60, 30));

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 60, 30));

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 60, 30));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 60, 30));

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 60, 30));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 60, 30));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 60, 30));

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 60, 30));

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 60, 30));

        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 60, 30));

        jTextField27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 60, 30));

        jTextField28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 60, 30));

        jTextField29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 60, 30));

        jTextField30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 60, 30));

        jTextField32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 390, 140, 40));

        jTextField33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 40, 30));

        jTextField34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 30));

        jTextField35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 40, 30));

        jTextField37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 40, 30));

        jTextField38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 40, 30));

        jTextField36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 40, 30));

        jTextField39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 40, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("GANTT CHART");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 160, -1));

        jTextField40.setEditable(false);
        jTextField40.setBackground(new java.awt.Color(51, 255, 255));
        jTextField40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField40.setText("     ");
        jTextField40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jTextField40.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 40));

        jTextField41.setBackground(new java.awt.Color(255, 153, 153));
        jTextField41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField41.setText("     ");
        jTextField41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 40));

        jTextField42.setBackground(new java.awt.Color(255, 51, 0));
        jTextField42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField42.setText("      ");
        jTextField42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, 40));

        jTextField43.setBackground(new java.awt.Color(102, 102, 255));
        jTextField43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField43.setText("     ");
        jTextField43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 90, 40));

        jTextField44.setBackground(new java.awt.Color(0, 255, 0));
        jTextField44.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField44.setText("      ");
        jTextField44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 90, 40));

        jTextField45.setBackground(new java.awt.Color(255, 255, 0));
        jTextField45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField45.setText("      ");
        jTextField45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 90, 40));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SIMULATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, 40));

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 110, 40));

        jTextField31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CPU SCHEDULING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 310, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("SHORTES JOB FIRST");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 170, 60));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("MAIN MENU");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MS");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 30, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MS");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 30, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jayson\\Desktop\\picture\\Buscar-en-Google-circuit-board-by-xxariesxx-durab-http-orig-d-wallpaper-wp-PIC-MCH050316-1024x576.png")); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.black));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1020, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
        
     
        
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(jTextField1.getText().isEmpty()||jTextField2.getText().isEmpty()||jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty()||jTextField6.getText().isEmpty()||jTextField7.getText().isEmpty()||jTextField8.getText().isEmpty()||jTextField9.getText().isEmpty()||jTextField10.getText().isEmpty()||jTextField11.getText().isEmpty()||jTextField12.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null,"INCOMPLETE INPUT","PLEASE ENTER A NUMBER",JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            
            
            int at[]=new int[6];
            int ct[]=new int[6];
            int bt[]=new int[6];
            int ct1[]=new int[6];
            int ta[]=new int[6];
            int wt[]=new int[6];
            float ata=0,awt=0;  
            String process[]={"P1","P2","P3","P4","P5","P6"};
            
            
            int x,y,min = 0,temp;
            String temp1;
            int btime=0,k=1,loc=0;
            
            at[0]=Integer.parseInt(jTextField1.getText());
            at[1]=Integer.parseInt(jTextField2.getText());
            at[2]=Integer.parseInt(jTextField3.getText());
            at[3]=Integer.parseInt(jTextField4.getText());
            at[4]=Integer.parseInt(jTextField5.getText());
            at[5]=Integer.parseInt(jTextField6.getText());
            
            bt[0]=Integer.parseInt(jTextField7.getText());
            bt[1]=Integer.parseInt(jTextField8.getText());
            bt[2]=Integer.parseInt(jTextField9.getText());
            bt[3]=Integer.parseInt(jTextField10.getText());
            bt[4]=Integer.parseInt(jTextField11.getText());
            bt[5]=Integer.parseInt(jTextField12.getText());
          
            for(x=0;x<6;x++){
                for(y=0;y<6;y++){
                    
                    if(at[x]<at[y]){
                        
                        temp1=process[y];
                        process[y]=process[x];
                        process[x]=temp1;
                        
                        temp=at[y];
                        at[y]=at[x];
                        at[x]=temp;
                        
                        temp=bt[y];
                        bt[y]=bt[x];
                        bt[x]=temp;
                    }
                    
                    
                    if(at[y]==at[x]){
                        
                       if(bt[x]>bt[y]){
                           
                        temp1=process[y];
                        process[y]=process[x];
                        process[x]=temp1;
                        
                        temp=at[y];
                        at[y]=at[x];
                        at[x]=temp;
                        
                        temp=bt[y];
                        bt[y]=bt[x];
                        bt[x]=temp; 
                       } 
                        
                    }
                    
                }
              
            }
              
           
            for(x=0;x<5;x++){
                
                    btime=btime+bt[x];
                    
                            
                for(y=k;y<6;y++){
                    
                    if(btime>=at[y]){
                        min=bt[k];
                        
                        if(min>=bt[y]){
                            
                            min=bt[y];
                            loc=y;
                        }
                        
                        else{
                            
                        temp1=process[loc];
                        process[loc]=process[k];
                        process[k]=temp1;
                        
                        temp=at[loc];
                        at[loc]=at[k];
                        at[k]=temp;
                        
                        temp=bt[loc];
                        bt[loc]=bt[k];
                        bt[k]=temp; 
                            
                        }
                        
                       
                    }
                    
                    
                
                 
                    if(min==bt[loc]){
                    
                  
                    
                        temp1=process[loc];
                        process[loc]=process[k];
                        process[k]=temp1;
                        
                        temp=at[loc];
                        at[loc]=at[k];
                        at[k]=temp;
                        
                        temp=bt[loc];
                        bt[loc]=bt[k];
                        bt[k]=temp;   
                    
                    }
                }        
                k++;
            }
            
            
            
            
            
            
            
            jTextField40.setText(""+process[0]);
            jTextField41.setText(""+process[1]);
            jTextField42.setText(""+process[2]);
            jTextField43.setText(""+process[3]);
            jTextField44.setText(""+process[4]);
            jTextField45.setText(""+process[5]);
            
            
            
           ct[0]=at[0]+bt[0];
            
            for(x=0;x<5;x++){
                ct[x+1]=ct[x]+bt[x+1];
                
            }
            
            int initial=at[0];
            
            jTextField33.setText(""+initial);
            jTextField34.setText(""+ct[0]);
            jTextField35.setText(""+ct[1]);
            jTextField36.setText(""+ct[2]);
            jTextField37.setText(""+ct[3]);
            jTextField38.setText(""+ct[4]);
            jTextField39.setText(""+ct[5]);
            
            
             String processtemp[]={"P1","P2","P3","P4","P5","P6"};
            
            for(x=0;x<6;x++){
                for(y=0;y<6;y++){
                    
                    if(processtemp[x].equals(process[y])){
                        
                        ct1[x]=ct[y];
                    }
                }
            }
            
            jTextField13.setText(""+ct1[0]);
            jTextField14.setText(""+ct1[1]);
            jTextField15.setText(""+ct1[2]);
            jTextField16.setText(""+ct1[3]);
            jTextField17.setText(""+ct1[4]);
            jTextField18.setText(""+ct1[5]);
            
            at[0]=Integer.parseInt(jTextField1.getText());
            at[1]=Integer.parseInt(jTextField2.getText());
            at[2]=Integer.parseInt(jTextField3.getText());
            at[3]=Integer.parseInt(jTextField4.getText());
            at[4]=Integer.parseInt(jTextField5.getText());
            at[5]=Integer.parseInt(jTextField6.getText());
            
           for(x=0;x<6;x++){
               
               ta[x]=ct1[x]-at[x];
               
           }
           
            jTextField19.setText(""+ta[0]);
            jTextField20.setText(""+ta[1]);
            jTextField21.setText(""+ta[2]);
            jTextField22.setText(""+ta[3]);
            jTextField23.setText(""+ta[4]);
            jTextField24.setText(""+ta[5]);
            
            bt[0]=Integer.parseInt(jTextField7.getText());
            bt[1]=Integer.parseInt(jTextField8.getText());
            bt[2]=Integer.parseInt(jTextField9.getText());
            bt[3]=Integer.parseInt(jTextField10.getText());
            bt[4]=Integer.parseInt(jTextField11.getText());
            bt[5]=Integer.parseInt(jTextField12.getText());
            
            for(x=0;x<6;x++){
                
                wt[x]=ta[x]-bt[x];
                
            }

            jTextField25.setText(""+wt[0]);
            jTextField26.setText(""+wt[1]);
            jTextField27.setText(""+wt[2]);
            jTextField28.setText(""+wt[3]);
            jTextField29.setText(""+wt[4]);
            jTextField30.setText(""+wt[5]);
            
            for(x=0;x<6;x++){
                
                ata=ata+ta[x];
                awt=awt+wt[x];
            }
           
            float average_ta = (float)ata/6;
            float average_wt = (float)awt/6;
            
            jTextField31.setText(String.format("%.2f",average_ta));
            jTextField32.setText(String.format("%.2f",average_wt));
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
      jTextField1.setText("");
      jTextField2.setText("");
      jTextField3.setText("");
      jTextField4.setText("");
      jTextField5.setText("");
      jTextField6.setText("");
      jTextField7.setText("");
      jTextField8.setText("");
      jTextField9.setText("");
      jTextField10.setText("");
      jTextField11.setText("");
      jTextField12.setText("");
      jTextField13.setText("");
      jTextField14.setText("");
      jTextField15.setText("");
      jTextField16.setText("");
      jTextField17.setText("");
      jTextField18.setText("");
      jTextField19.setText("");
      jTextField20.setText("");
      jTextField21.setText("");
      jTextField22.setText("");
      jTextField23.setText("");
      jTextField24.setText("");
      jTextField25.setText("");
      jTextField26.setText("");
      jTextField27.setText("");
      jTextField28.setText("");
      jTextField29.setText("");
      jTextField30.setText("");
      jTextField31.setText("");
      jTextField32.setText("");
      jTextField33.setText("");
      jTextField34.setText("");
      jTextField35.setText("");
      jTextField36.setText("");
      jTextField37.setText("");
      jTextField38.setText("");
      jTextField39.setText("");
      jTextField40.setText("");
      jTextField41.setText("");
      jTextField42.setText("");
      jTextField43.setText("");
      jTextField44.setText("");
      jTextField45.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField1.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField1.setEditable(true); 
            
        }
           
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField2.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField2.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField3.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField3.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField4.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField4.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField5.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField5.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField6.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField6.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField7.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField7.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField8.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField8.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField9.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField9.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField10.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField10.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField11.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
            
        }
        else{
            
          jTextField11.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
        
         char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            jTextField12.setEditable(false);
            JOptionPane.showMessageDialog(null,"Please Enter Number Only","   INVALID INPUT",JOptionPane.ERROR_MESSAGE);
           
        }
        else{
            
          jTextField12.setEditable(true); 
            
        }
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
            new MENU().setVisible(true);
            this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Algo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Algo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
